version: '3'

services:
  java_app:
    image: nestorgacr/bank_account_app:dk
    container_name: java_container_bank
    ports:
      - "8086:8086"
    working_dir: /app
    networks:
      - bankNet
    depends_on:
      - rabbitmq
      - mongodb

  java_service:
    image: nestorgacr/bank_account_service:latest
    environment:
      - RABBIT_URI=amqp://rabbit_user:b5x26z4p@192.168.65.3:5672
      - MONGO_URI=mongodb://192.168.65.3:27017/
    container_name: java_container_bank_service
    ports:
      - "8087:8086"
    working_dir: /app
    networks:
      - bankNet
    depends_on:
      - rabbitmq
      - mongodb

  mongodb:
    image: mongo:7.0.4
    container_name: mongodb_container_bank
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - bankNet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container_bank
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: b5x26z4p
    networks:
      - bankNet

networks:
  bankNet:

volumes:
  appBank:
