apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-acount-log
spec:
  replicas: 1
  selector:
    matchLabels:
      role: bank-acount-log
  template:
    metadata:
      labels:
        role: bank-acount-log
    spec:
      containers:
        - name: bank-acount-log
          image: nestorgacr/bank_account_service:latest
          ports:
            - containerPort: 8087
          env:
            - name: RABBIT_URI
              valueFrom:
                secretKeyRef:
                  name: bank-acount-log-secrets
                  key: RABBIT_URI
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: bank-acount-log-secrets
                  key: MONGO_URI
