apiVersion: v1
kind: Service
metadata:
  name: bank-acount-log-service
spec:
  selector:
    role: bank-acount-log
  ports:
    - name: app-port
      port: 8087
      targetPort: 8087
      nodePort: 30040
  type: LoadBalancer

     